// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: keys.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKey = `-- name: CreateKey :one
INSERT INTO keys (reservation_id, user_id, key_code, device_id, valid_from, valid_until)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, reservation_id, user_id, key_code, device_id, valid_from, valid_until, created_at, updated_at
`

type CreateKeyParams struct {
	ReservationID pgtype.UUID      `json:"reservation_id"`
	UserID        pgtype.UUID      `json:"user_id"`
	KeyCode       string           `json:"key_code"`
	DeviceID      string           `json:"device_id"`
	ValidFrom     pgtype.Timestamp `json:"valid_from"`
	ValidUntil    pgtype.Timestamp `json:"valid_until"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (Key, error) {
	row := q.db.QueryRow(ctx, createKey,
		arg.ReservationID,
		arg.UserID,
		arg.KeyCode,
		arg.DeviceID,
		arg.ValidFrom,
		arg.ValidUntil,
	)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.UserID,
		&i.KeyCode,
		&i.DeviceID,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKeyByReservationID = `-- name: GetKeyByReservationID :one
SELECT id, reservation_id, user_id, key_code, device_id, valid_from, valid_until, created_at, updated_at
FROM keys
WHERE reservation_id = $1 LIMIT 1
`

func (q *Queries) GetKeyByReservationID(ctx context.Context, reservationID pgtype.UUID) (Key, error) {
	row := q.db.QueryRow(ctx, getKeyByReservationID, reservationID)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.UserID,
		&i.KeyCode,
		&i.DeviceID,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveKeysByUserID = `-- name: ListActiveKeysByUserID :many
SELECT id, reservation_id, user_id, key_code, device_id, valid_from, valid_until, created_at, updated_at
FROM keys
WHERE user_id = $1
  AND DATE(valid_from) <= CURRENT_DATE
  AND DATE(valid_until) >= CURRENT_DATE
ORDER BY valid_from DESC
`

func (q *Queries) ListActiveKeysByUserID(ctx context.Context, userID pgtype.UUID) ([]Key, error) {
	rows, err := q.db.Query(ctx, listActiveKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Key
	for rows.Next() {
		var i Key
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.UserID,
			&i.KeyCode,
			&i.DeviceID,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeysByUserID = `-- name: ListKeysByUserID :many
SELECT id, reservation_id, user_id, key_code, device_id, valid_from, valid_until, created_at, updated_at
FROM keys
WHERE user_id = $1
ORDER BY valid_from DESC
`

func (q *Queries) ListKeysByUserID(ctx context.Context, userID pgtype.UUID) ([]Key, error) {
	rows, err := q.db.Query(ctx, listKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Key
	for rows.Next() {
		var i Key
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.UserID,
			&i.KeyCode,
			&i.DeviceID,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
