// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             pgtype.UUID      `json:"id"`
	Email          string           `json:"email"`
	HashedPassword []byte           `json:"hashed_password"`
	Name           string           `json:"name"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
