// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reservations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (user_id, room_id, start_date, end_date, total_price, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, room_id, start_date, end_date, total_price, status, created_at, updated_at
`

type CreateReservationParams struct {
	UserID     pgtype.UUID      `json:"user_id"`
	RoomID     int64            `json:"room_id"`
	StartDate  pgtype.Timestamp `json:"start_date"`
	EndDate    pgtype.Timestamp `json:"end_date"`
	TotalPrice int64            `json:"total_price"`
	Status     string           `json:"status"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.UserID,
		arg.RoomID,
		arg.StartDate,
		arg.EndDate,
		arg.TotalPrice,
		arg.Status,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT id, user_id, room_id, start_date, end_date, total_price, status, created_at, updated_at
FROM reservations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReservationsByUserID = `-- name: ListReservationsByUserID :many
SELECT id, user_id, room_id, start_date, end_date, total_price, status, created_at, updated_at
FROM reservations
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReservationsByUserID(ctx context.Context, userID pgtype.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoomID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE reservations
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, room_id, start_date, end_date, total_price, status, created_at, updated_at
`

type UpdateReservationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus, arg.ID, arg.Status)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
